spring:
  datasource:
    url:  jdbc:h2:mem:~/velog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
post:
  image:
    upload:
      path: /Users/yoonezi/Desktop/images/
#
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace