spring:
  datasource:
    url:  jdbc:h2:mem:~/velog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 10
  data:
    redis:
      host: localhost
      port: 6379
post:
  image:
    upload:
      path: /Users/yoonezi/Desktop/images/
jwt:
  secret-key: wepqieqiopeiwqpepowqiopwqiopeiowqpieopqwopieqweoipuqweiopepqioepqiopeiqopwwpqoi
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace